name: PaperCardMirai
version: '${project.version}'
main: cn.paper_card.mirai.PaperCardMirai
api-version: '1.20'
author: Paper99
folia-supported: true

commands:
  paper-card-mirai:
    aliases: [ pcmirai ]
